create table if not exists weather_days
(
    id                      bigint generated by default as identity primary key,
    uuid                    uuid                     not null default uuid_generate_v4(),
    created_at              timestamp with time zone not null default (now() at time zone 'utc'),
    updated_at              timestamp with time zone not null default (now() at time zone 'utc'),
    deleted_at              timestamp with time zone,
    version                 bigint                   not null default 1,

    date                    timestamp with time zone not null default (now() at time zone 'utc'), -- this will be the day of the year

    location                varchar(255)             not null,
    region                  varchar(255)             not null,
    country                 varchar(255)             not null,
    latlon                  point                    not null,
    unit                    varchar(10)              not null,

    astro_sunrise           timestamp with time zone not null,
    astro_sunset            timestamp with time zone not null,
    astro_moonrise          timestamp with time zone not null,
    astro_moonset           timestamp with time zone not null,
    astro_moon_phase        varchar(25)              not null,
    astro_moon_illumination double precision         not null,

    mintemp                 double precision         not null,
    maxtemp                 double precision         not null,
    avgtemp                 double precision         not null,
    totalsnow               double precision         not null,
    sunhour                 double precision         not null,
    uv_index                double precision         not null
);

create table if not exists weather_hourly
(
    id                   bigint generated by default as identity primary key,
    uuid                 uuid                     not null default uuid_generate_v4(),
    created_at           timestamp with time zone not null default (now() at time zone 'utc'),
    updated_at           timestamp with time zone not null default (now() at time zone 'utc'),
    deleted_at           timestamp with time zone,
    weather_days_id      bigint                   not null references weather_days,
    /**
    Returns the time as a number in 24h format:
    0 = 12:00 AM
    100 = 1:00 AM
    200 = 2:00 AM
    ...
    1200 = 12:00 PM
    1300 = 1:00 PM
    etc.
    we need to convert this to a timestamp date
    */
    hour                 varchar(10)              not null,
    time                 timestamp with time zone not null,
    temperature          double precision         not null,
    wind_speed           double precision         not null,
    wind_degree          double precision         not null,
    wind_dir             varchar(255)             not null default 'N',
    weather_code         int                      not null,
    weather_descriptions jsonb,
    precip               double precision         not null,
    humidity             double precision         not null,
    visibility           double precision         not null,
    pressure             double precision         not null,
    cloudcover           double precision         not null,
    heatindex            double precision         not null,
    dewpoint             double precision         not null,
    windchill            double precision         not null,
    windgust             double precision         not null,
    feelslike            double precision         not null,
    chanceofrain         double precision         not null,
    chanceofremdry       double precision         not null,
    chanceofwindy        double precision         not null,
    chanceofovercast     double precision         not null,
    chanceofsunshine     double precision         not null,
    chanceoffrost        double precision         not null,
    chanceofhightemp     double precision         not null,
    chanceoffog          double precision         not null,
    chanceofsnow         double precision         not null,
    chanceofthunder      double precision         not null,
    uv_index             double precision         not null
)